// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: service_area.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaType string `protobuf:"bytes,1,opt,name=area_type,json=areaType,proto3" json:"area_type,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_area_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_area_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_service_area_proto_rawDescGZIP(), []int{0}
}

func (x *GetAreaRequest) GetAreaType() string {
	if x != nil {
		return x.AreaType
	}
	return ""
}

func (x *GetAreaRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetAreaInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string                      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data []*GetAreaInfoResponse_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAreaInfoResponse) Reset() {
	*x = GetAreaInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_area_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaInfoResponse) ProtoMessage() {}

func (x *GetAreaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_area_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAreaInfoResponse) Descriptor() ([]byte, []int) {
	return file_service_area_proto_rawDescGZIP(), []int{1}
}

func (x *GetAreaInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAreaInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAreaInfoResponse) GetData() []*GetAreaInfoResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAreaInfoResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAreaInfoResponse_Data) Reset() {
	*x = GetAreaInfoResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_area_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaInfoResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaInfoResponse_Data) ProtoMessage() {}

func (x *GetAreaInfoResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_service_area_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaInfoResponse_Data.ProtoReflect.Descriptor instead.
func (*GetAreaInfoResponse_Data) Descriptor() ([]byte, []int) {
	return file_service_area_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAreaInfoResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAreaInfoResponse_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_service_area_proto protoreflect.FileDescriptor

var file_service_area_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3f, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x72, 0x65, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x99, 0x01, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2a, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x4d, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_area_proto_rawDescOnce sync.Once
	file_service_area_proto_rawDescData = file_service_area_proto_rawDesc
)

func file_service_area_proto_rawDescGZIP() []byte {
	file_service_area_proto_rawDescOnce.Do(func() {
		file_service_area_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_area_proto_rawDescData)
	})
	return file_service_area_proto_rawDescData
}

var file_service_area_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_area_proto_goTypes = []interface{}{
	(*GetAreaRequest)(nil),           // 0: grpc.GetAreaRequest
	(*GetAreaInfoResponse)(nil),      // 1: grpc.GetAreaInfoResponse
	(*GetAreaInfoResponse_Data)(nil), // 2: grpc.GetAreaInfoResponse.Data
}
var file_service_area_proto_depIdxs = []int32{
	2, // 0: grpc.GetAreaInfoResponse.data:type_name -> grpc.GetAreaInfoResponse.Data
	0, // 1: grpc.ServiceArea.GetAreaInfo:input_type -> grpc.GetAreaRequest
	1, // 2: grpc.ServiceArea.GetAreaInfo:output_type -> grpc.GetAreaInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_area_proto_init() }
func file_service_area_proto_init() {
	if File_service_area_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_area_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_area_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_area_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaInfoResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_area_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_area_proto_goTypes,
		DependencyIndexes: file_service_area_proto_depIdxs,
		MessageInfos:      file_service_area_proto_msgTypes,
	}.Build()
	File_service_area_proto = out.File
	file_service_area_proto_rawDesc = nil
	file_service_area_proto_goTypes = nil
	file_service_area_proto_depIdxs = nil
}
